package com.sxy.uclock.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.sxy.uclock.db.User;
import com.sxy.uclock.db.WorkAndRestTemplate;
import com.sxy.uclock.db.WorkAndRestDetails;

import com.sxy.uclock.db.UserDao;
import com.sxy.uclock.db.WorkAndRestTemplateDao;
import com.sxy.uclock.db.WorkAndRestDetailsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig workAndRestTemplateDaoConfig;
    private final DaoConfig workAndRestDetailsDaoConfig;

    private final UserDao userDao;
    private final WorkAndRestTemplateDao workAndRestTemplateDao;
    private final WorkAndRestDetailsDao workAndRestDetailsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        workAndRestTemplateDaoConfig = daoConfigMap.get(WorkAndRestTemplateDao.class).clone();
        workAndRestTemplateDaoConfig.initIdentityScope(type);

        workAndRestDetailsDaoConfig = daoConfigMap.get(WorkAndRestDetailsDao.class).clone();
        workAndRestDetailsDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        workAndRestTemplateDao = new WorkAndRestTemplateDao(workAndRestTemplateDaoConfig, this);
        workAndRestDetailsDao = new WorkAndRestDetailsDao(workAndRestDetailsDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(WorkAndRestTemplate.class, workAndRestTemplateDao);
        registerDao(WorkAndRestDetails.class, workAndRestDetailsDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        workAndRestTemplateDaoConfig.getIdentityScope().clear();
        workAndRestDetailsDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public WorkAndRestTemplateDao getWorkAndRestTemplateDao() {
        return workAndRestTemplateDao;
    }

    public WorkAndRestDetailsDao getWorkAndRestDetailsDao() {
        return workAndRestDetailsDao;
    }

}
