package com.sxy.uclock.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.sxy.uclock.db.WorkAndRestDetails;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WORK_AND_REST_DETAILS".
*/
public class WorkAndRestDetailsDao extends AbstractDao<WorkAndRestDetails, Long> {

    public static final String TABLENAME = "WORK_AND_REST_DETAILS";

    /**
     * Properties of entity WorkAndRestDetails.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property DetailsID = new Property(0, Long.class, "detailsID", true, "DETAILS_ID");
        public final static Property TemplateID = new Property(1, Long.class, "templateID", false, "TEMPLATE_ID");
        public final static Property DetailsType = new Property(2, int.class, "detailsType", false, "DETAILS_TYPE");
        public final static Property DetailsDate = new Property(3, String.class, "detailsDate", false, "DETAILS_DATE");
        public final static Property DetailsTime = new Property(4, String.class, "detailsTime", false, "DETAILS_TIME");
        public final static Property DetailsDescribe = new Property(5, String.class, "detailsDescribe", false, "DETAILS_DESCRIBE");
        public final static Property DetailsIsUsing = new Property(6, Boolean.class, "detailsIsUsing", false, "DETAILS_IS_USING");
    };

    private DaoSession daoSession;

    private Query<WorkAndRestDetails> workAndRestTemplate_WarDetailsQuery;

    public WorkAndRestDetailsDao(DaoConfig config) {
        super(config);
    }
    
    public WorkAndRestDetailsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WORK_AND_REST_DETAILS\" (" + //
                "\"DETAILS_ID\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: detailsID
                "\"TEMPLATE_ID\" INTEGER," + // 1: templateID
                "\"DETAILS_TYPE\" INTEGER NOT NULL ," + // 2: detailsType
                "\"DETAILS_DATE\" TEXT," + // 3: detailsDate
                "\"DETAILS_TIME\" TEXT," + // 4: detailsTime
                "\"DETAILS_DESCRIBE\" TEXT," + // 5: detailsDescribe
                "\"DETAILS_IS_USING\" INTEGER);"); // 6: detailsIsUsing
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WORK_AND_REST_DETAILS\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, WorkAndRestDetails entity) {
        stmt.clearBindings();
 
        Long detailsID = entity.getDetailsID();
        if (detailsID != null) {
            stmt.bindLong(1, detailsID);
        }
 
        Long templateID = entity.getTemplateID();
        if (templateID != null) {
            stmt.bindLong(2, templateID);
        }
        stmt.bindLong(3, entity.getDetailsType());
 
        String detailsDate = entity.getDetailsDate();
        if (detailsDate != null) {
            stmt.bindString(4, detailsDate);
        }
 
        String detailsTime = entity.getDetailsTime();
        if (detailsTime != null) {
            stmt.bindString(5, detailsTime);
        }
 
        String detailsDescribe = entity.getDetailsDescribe();
        if (detailsDescribe != null) {
            stmt.bindString(6, detailsDescribe);
        }
 
        Boolean detailsIsUsing = entity.getDetailsIsUsing();
        if (detailsIsUsing != null) {
            stmt.bindLong(7, detailsIsUsing ? 1L: 0L);
        }
    }

    @Override
    protected void attachEntity(WorkAndRestDetails entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public WorkAndRestDetails readEntity(Cursor cursor, int offset) {
        WorkAndRestDetails entity = new WorkAndRestDetails( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // detailsID
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // templateID
            cursor.getInt(offset + 2), // detailsType
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // detailsDate
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // detailsTime
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // detailsDescribe
            cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0 // detailsIsUsing
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, WorkAndRestDetails entity, int offset) {
        entity.setDetailsID(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTemplateID(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setDetailsType(cursor.getInt(offset + 2));
        entity.setDetailsDate(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDetailsTime(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setDetailsDescribe(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setDetailsIsUsing(cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(WorkAndRestDetails entity, long rowId) {
        entity.setDetailsID(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(WorkAndRestDetails entity) {
        if(entity != null) {
            return entity.getDetailsID();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "warDetails" to-many relationship of WorkAndRestTemplate. */
    public List<WorkAndRestDetails> _queryWorkAndRestTemplate_WarDetails(Long templateID) {
        synchronized (this) {
            if (workAndRestTemplate_WarDetailsQuery == null) {
                QueryBuilder<WorkAndRestDetails> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.TemplateID.eq(null));
                workAndRestTemplate_WarDetailsQuery = queryBuilder.build();
            }
        }
        Query<WorkAndRestDetails> query = workAndRestTemplate_WarDetailsQuery.forCurrentThread();
        query.setParameter(0, templateID);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getWorkAndRestTemplateDao().getAllColumns());
            builder.append(" FROM WORK_AND_REST_DETAILS T");
            builder.append(" LEFT JOIN WORK_AND_REST_TEMPLATE T0 ON T.\"TEMPLATE_ID\"=T0.\"TEMPLATE_ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected WorkAndRestDetails loadCurrentDeep(Cursor cursor, boolean lock) {
        WorkAndRestDetails entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        WorkAndRestTemplate workAndRestTemplate = loadCurrentOther(daoSession.getWorkAndRestTemplateDao(), cursor, offset);
        entity.setWorkAndRestTemplate(workAndRestTemplate);

        return entity;    
    }

    public WorkAndRestDetails loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<WorkAndRestDetails> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<WorkAndRestDetails> list = new ArrayList<WorkAndRestDetails>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<WorkAndRestDetails> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<WorkAndRestDetails> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
